name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Fetch & extract DepotDownloader
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: SteamRE/DepotDownloader
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build.yml
        workflow_conclusion: success
        name: DepotDownloader-Windows
        path: ./DepotDownloader-Windows

    - name: Fetch VRChat binaries
      run: dotnet .\DepotDownloader-Windows\DepotDownloader.dll -app 438100 -depot 438101 -dir ./VRChat -username $env:DEPOTDL_USERNAME -password $env:DEPOTDL_PASSWORD
      env:
        DEPOTDL_USERNAME: ${{ secrets.DEPOTDL_USERNAME }}
        DEPOTDL_PASSWORD: ${{ secrets.DEPOTDL_PASSWORD }}
    
    - name: Fetch Cpp2IL
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: SamboyCoding/Cpp2IL
        branch: new-analysis
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: dotnet-core.yml
        workflow_conclusion: success
        name: Cpp2IL-Windows-Netframework472
        path: ./Cpp2IL-Windows-Netframework472

    - name: Fetch MelonLoader
      uses: robinraju/release-downloader@v1.3
      with:
        repository: LavaGang/MelonLoader
        tag: "v0.5.1"
        fileName: MelonLoader.x64.zip
        out-file-path: ./

    - name: Fetch Il2CppAssemblyUnhollower
      uses: robinraju/release-downloader@v1.3
      with:
        repository: knah/Il2CppAssemblyUnhollower
        latest: true
        out-file-path: ./Il2CppAssemblyUnhollower

    - name: Fetch Unity dependencies
      run: |
        New-Item -Path ./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator -ItemType Directory
        Invoke-WebRequest https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2019.4.31.zip -OutFile ./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/UnityDependencies/2019.4.31.zip
        Expand-Archive ./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/UnityDependencies/2019.4.31.zip

    - name: Fetch deobfuscation map
      run: |
        New-Item -Path ./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator -ItemType Directory
        Invoke-WebRequest https://github.com/LavaGang/Deobfuscation-Maps/raw/master/VRChat/1159.0.csv.gz -OutFile ./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/DeobfuscationMap.csv.gz

    - name: Install MelonLoader
      run: |
        Expand-Archive ./MelonLoader.x64.zip
        Move-Item ./MelonLoader.x64/* ./VRChat
        New-Item -Path ./VRChat/Mods -ItemType Directory
        Invoke-WebRequest https://api.vrcmg.com/v0/mods/231/VRChatUtilityKit.dll -OutFile ./VRChat/Mods/VRChatUtilityKit.dll

    - name: Generate assemblies
      run: ./Cpp2IL-Windows-Netframework472/Cpp2IL.exe --game-path ./VRChat --output-root ./Cpp2IL-Windows-Netframework472/cpp2il_out --just-give-me-dlls-asap-dammit

    - name: Unhollow assemblies
      run: |
        ./AssemblyUnhollower.exe --input=./Cpp2IL-Windows-Netframework472/cpp2il_out \
                                 --output=./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/Il2CppAssemblyUnhollower/Managed \
                                 --mscorlib=./VRChat/MelonLoader/Managed/mscorlib.dll" \
                                 --unity=./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/UnityDependencies \
                                 --gameassembly=./VRChat/GameAssembly.dll \
                                 --rename-map=./VRChat/MelonLoader/Dependencies/Il2CppAssemblyGenerator/DeobfuscationMap.csv.gz \
                                 --blacklist-assembly=Mono.Security \
                                 --blacklist-assembly=Newtonsoft.Json \
                                 --blacklist-assembly=Valve.Newtonsoft.Json \

    - name: Build
      run: dotnet build -p:RunningInGitHubWorkflow=True -p:Configuration=Release

    - name: Get short commit SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.short-sha.outputs.sha }}.zip
        path: ./bin/