name: Build & upload artifacts
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Build
      run: dotnet build -p:RunningInGitHubWorkflow=True -p:Configuration=Release

    - run: $SHORT_SHA=$GITHUB_SHA.SubString(0,7)
      shell: pwsh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.SHORT_SHA }}.zip
        path: bin/