name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Fetch VRChat binaries
        uses: Skippeh/steamfetch-action@v1
        with:
          app: 438100
          depot: 438101
          manifest: '682916728963337440' # VRChat 1192
          dir: ${{ github.workspace }}/VRChat
          os: windows
          osarch: 64
          username: ${{ secrets.DEPOTDL_USERNAME }}
          password: ${{ secrets.DEPOTDL_PASSWORD }}
          files: |
                VRChat.exe
                GameAssembly.dll
                VRChat_Data\globalgamemanagers
                VRChat_Data\il2cpp_data\Metadata\global-metadata.dat

      - name: Generate libraries
        uses: tetra-fox/ml-gen@main
        with:
          game: vrchat
          game_path: ${{ github.workspace }}/VRChat
          game_executable: VRChat

      - name: Download VRChatUtilityKit
        run: wget -q -P ${{ github.workspace }}/VRChat/Mods https://api.vrcmg.com/v0/mods/231/VRChatUtilityKit.dll

      - name: Build
        run: dotnet build -p:CI=True -p:Configuration=Release

      - name: Get short commit SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VRCMods.${{ steps.short-sha.outputs.sha }}.CI
          path: bin/
