name: Build & upload artifacts
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
      
    - name: Build
      run: dotnet build -p:RunningInGitHubWorkflow=True -p:Configuration=Release

    - name: Get short commit SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: VRCMods.${{ steps.short-sha.outputs.sha }}.CI
        path: bin/
